// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import ReactDOM from 'react-dom/client';
import { Amplify, ResourcesConfig } from 'aws-amplify';
import './theme.css';
import './styles.css';
import './i18n/i18n';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { App } from './App.tsx';
import React from 'react';
import { BrowserRouter } from 'react-router-dom';
import { UserProvider } from './contexts/UserContext.tsx';
import { useConfigStore } from './stores/config-store.ts';
import { usePreferencesStore, applyThemeClass } from './stores/preferences-store.ts';

/**
 * Read the configuration .json file that was generated by the custom resource during deployment.
 * If running in development mode, also enable mock-service-worker to intercept defined http requests.
 */
const getRuntimeConfig = async () => {
    let runtimeConfig: any = {};
    try {
        const response = await fetch('/runtimeConfig.json');
        runtimeConfig = await response.json();
    } catch (e) {
        console.log(e);
    }

    return runtimeConfig;
};

getRuntimeConfig().then((json) => {
    const awsconfig: ResourcesConfig = {
        Auth: {
            Cognito: {
                userPoolId: json.UserPoolId,
                userPoolClientId: json.UserPoolClientId,
                loginWith: {
                    oauth: {
                        domain: json.CognitoDomain,
                        scopes: ['openid', 'aws.cognito.signin.user.admin', 'email'],
                        redirectSignIn: [json.CognitoRedirectUrl],
                        redirectSignOut: [json.CognitoRedirectUrl],
                        responseType: 'code'
                    }
                }
            }
        },
        API: {
            REST: {
                'solution-api': {
                    endpoint: json.RestApiEndpoint
                }
            }
        }
    };
    Amplify.configure(awsconfig);

    useConfigStore.getState().setRuntimeConfig(json);

    // Apply the persisted (or system-derived) theme before first paint
    applyThemeClass(usePreferencesStore.getState().darkMode);

    const queryClient = new QueryClient({
        defaultOptions: {
            queries: {
                refetchOnWindowFocus: false
            }
        }
    });

    // Set window.global to window.globalThis to ensure global object compatibility
    // This is needed for certain libraries that expect a global object to be available
    window.global = window.globalThis;

    const root = ReactDOM.createRoot(document.getElementById('root') as HTMLElement);

    root.render(
        <React.StrictMode>
            <BrowserRouter>
                <QueryClientProvider client={queryClient}>
                    <UserProvider>
                        <App />
                    </UserProvider>
                </QueryClientProvider>
            </BrowserRouter>
        </React.StrictMode>
    );
});
